SELECT
	PRODUCT_GROUP
	,PRODUCT_TYPE
	,PRODUCT_NAME
	,DATE_TRUNC('MONTH',CREATION_DATE) AS CREATION_MONTH
	,COUNT(*) AS GROSS_ORDERS
	,COUNT_IF(IS_CONFIRMED = TRUE) AS NET_ORDERS
	,SUM(IS_CANCELLED::INTEGER) AS CANCELLED_ORDERS
	,SUM(GROSS_BASE_PROVISION + COALESCE(GROSS_PLACEMENT_PROVISION,0) + COALESCE(GROSS_PROPORTIONAL_PROVISION,0))
		AS GROSS_PROV
	,SUM(NET_BASE_PROVISION + COALESCE(NET_PLACEMENT_PROVISION,0) + COALESCE(NET_PROPORTIONAL_PROVISION,0))
		AS NET_PROV
	--
	,GROSS_ORDERS - NET_ORDERS - CANCELLED_ORDERS AS _DIFF
	,NET_PROV / GROSS_ORDERS AS _YIELD
FROM
	MARTS.MRT_ORDERS
GROUP BY
	ALL
