repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: /workspaces/analytics/.venv/bin/pylint
        language: system
        types: [python]
        require_serial: true
        args: ["-rn", "--rcfile=pyproject.toml"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
    # dbt-checkpoint has some flaws therefore custom hook for `dbt parse` is used
    # NOTE: For simplicity this hook always runs, regardless of whether dbt-related files are committed
  - repo: local
    hooks:
      - id: dbt_parse
        name: dbt_parse
        entry: bash -c 'source /workspaces/analytics/utils/hook_dbt_parse.sh'
        language: system
        types: [bash]
        require_serial: true
        always_run: true
    # Excluding files using regex necessary due to flaws of dbt-checkpoint
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.3
    hooks:
      - id: check-macro-arguments-have-desc
        exclude: '^(?!dbt_analytics/macros/)|^\.md$'
      - id: check-macro-has-description
        exclude: '^(?!dbt_analytics/macros/)|^\.md$'
      - id: check-model-columns-have-desc
        exclude: '^(?!dbt_analytics/models/)|^\.md$'
      - id: check-model-has-all-columns
        exclude: '^(?!dbt_analytics/models/)|^\.md$'
      - id: check-model-has-description
        exclude: '^(?!dbt_analytics/models/)|^\.md$'
      - id: check-model-has-properties-file
        exclude: '^(?!dbt_analytics/models/)|^\.md$'
      - id: check-model-has-tests
        exclude: '^(?!dbt_analytics/models/)|^\.md$'
      - id: check-script-has-no-table-name
        exclude: ^(?!dbt_analytics/models/)|^\.md$|^\.yml$'
      - id: check-script-ref-and-source
        exclude: ^(?!dbt_analytics/models/)|^\.md$|^\.yml$'
      - id: check-script-semicolon
        exclude: ^(?!dbt_analytics/models/)|^\.md$|^\.yml$'
      - id: check-source-columns-have-desc
        exclude: '^(?!dbt_analytics/models/stage/raw/)|^\.md$'
      - id: check-source-has-all-columns
        exclude: '^(?!dbt_analytics/models/stage/raw/)|^\.md$'
      - id: check-source-has-loader
        exclude: '^(?!dbt_analytics/models/stage/raw/)|^\.md$'
      - id: check-source-has-tests
        exclude: '^(?!dbt_analytics/models/stage/raw/)|^\.md$'
      - id: check-source-table-has-description
        exclude: '^(?!dbt_analytics/models/stage/raw/)|^\.md$'
