ci:
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
  autofix_prs: true
  autoupdate_branch: dev
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly
  skip:
    - pylint
    # dbt related hooks are ignored
    - dbt_debug
    - dbt_parse_docs_generate
    - check-macro-arguments-have-desc
    - check-macro-has-description
    - check-model-columns-have-desc
    - check-model-has-all-columns
    - check-model-has-description
    - check-model-has-properties-file
    - check-model-has-tests
    #- check-script-has-no-table-name
    - check-script-ref-and-source
    - check-script-semicolon
    - check-source-columns-have-desc
    - check-source-has-all-columns
    - check-source-has-loader
    - check-source-has-tests
    - check-source-table-has-description
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: ./.venv/bin/pylint
        language: system
        types: [python]
        require_serial: true
        args: ["-rn", "--rcfile=pyproject.toml"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  # NOTE: Shell script called by hook checks if any dbt related files are shown by `git status`
  - repo: local
    hooks:
      - id: dbt_debug
        name: dbt_debug
        entry: bash -c 'source ./utils/dbt_debug.sh'
        language: system
        types: [bash]
        require_serial: true
        always_run: true
    # dbt-checkpoint has some flaws therefore custom hook for `dbt_parse_docs_generate` is used
    # NOTE: Shell script called by hook checks if any dbt related files are shown by `git status`
  - repo: local
    hooks:
      - id: dbt_parse_docs_generate
        name: dbt_parse_docs_generate
        entry: bash -c 'source ./utils/dbt_parse_docs_generate.sh'
        language: system
        types: [bash]
        require_serial: true
        always_run: true
    # Excluding files using regex necessary due to flaws of dbt-checkpoint
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.3
    hooks:
      - id: check-macro-arguments-have-desc
        exclude: '^(?!dbt_analytics/macros/)|^\.md$'
      - id: check-macro-has-description
        exclude: '^(?!dbt_analytics/macros/)|^\.md$'
      - id: check-model-columns-have-desc
        exclude: '^(?!dbt_analytics/models/)|^\.md$'
      - id: check-model-has-all-columns
        exclude: '^(?!dbt_analytics/models/)|^\.md$'
      - id: check-model-has-description
        exclude: '^(?!dbt_analytics/models/)|^\.md$'
      - id: check-model-has-properties-file
        exclude: '^(?!dbt_analytics/models/)|^\.md$'
      - id: check-model-has-tests
        exclude: '^(?!dbt_analytics/models/)|^\.md$'
      #- id: check-script-has-no-table-name
      #  exclude: ^(?!dbt_analytics/models/)|^\.md$|^\.yml$'
      - id: check-script-ref-and-source
        exclude: ^(?!dbt_analytics/models/)|^\.md$|^\.yml$'
      - id: check-script-semicolon
        exclude: ^(?!dbt_analytics/models/)|^\.md$|^\.yml$'
      - id: check-source-columns-have-desc
        exclude: '^(?!dbt_analytics/models/stage/raw/)|^\.md$'
      - id: check-source-has-all-columns
        exclude: '^(?!dbt_analytics/models/stage/raw/)|^\.md$'
      - id: check-source-has-loader
        exclude: '^(?!dbt_analytics/models/stage/raw/)|^\.md$'
      - id: check-source-has-tests
        exclude: '^(?!dbt_analytics/models/stage/raw/)|^\.md$'
      - id: check-source-table-has-description
        exclude: '^(?!dbt_analytics/models/stage/raw/)|^\.md$'
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.0
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix
