repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: /workspaces/analytics/.venv/bin/pylint
        language: system
        types: [python]
        require_serial: true
        args: ["-rn", "--rcfile=pyproject.toml"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
    # dbt-checkpoint has some flaws therefore custom hook for `dbt parse` is used
    # NOTE: For simplicity this hook always runs, regardless of whether dbt-related files are committed
  - repo: local
    hooks:
      - id: dbt_parse
        name: dbt_parse
        entry: bash -c 'source /workspaces/analytics/utils/hook_dbt_parse.sh'
        language: system
        types: [bash]
        require_serial: true
        always_run: true
    # The following hooks would be valuable but are currently not functioning correctly (possibly in a future release):
    # check-model-has-all-columns
    # check-model-has-description
    # check-model-has-properties-file
    # check-model-has-tests
    # check-script-has-no-table-name
    # check-script-ref-and-source
    # check-script-semicolon
    # check-source-columns-have-desc
    # check-source-has-all-columns
    # check-source-has-loader
    # check-source-has-tests
    # check-source-table-has-description
    # -> Use just one hook to show-case how it would work
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.3
    hooks:
      - id: check-model-columns-have-desc
