CREATE OR REPLACE TEMP TABLE TMP AS
WITH CTE_TESTS AS (
	SELECT TABLE_NAME
	FROM
		INFORMATION_SCHEMA.TABLES -- noqa
	WHERE
		TABLE_SCHEMA = 'dbt_test__audit'
)

,CTE_FILTER AS (
	SELECT TABLE_NAME AS _TBL
	FROM
		INFORMATION_SCHEMA.TABLES --noqa
	WHERE
		TABLE_SCHEMA NOT IN ('main','RAW_DATA','dbt_test__audit')
)

SELECT
	STRING_SPLIT(TABLE_NAME,'__')[1] AS RELATED_DBT_OBJECT
	,STRING_SPLIT(TABLE_NAME,'__')[3] AS TEST_TYPE
FROM
	CTE_TESTS
WHERE
	RELATED_DBT_OBJECT IN (SELECT _TBL FROM CTE_FILTER) -- noqa
	AND
	LEN(STRING_SPLIT(TABLE_NAME,'__')) = 3
