SELECT
    _INT AS ORDER_ID
    -- ROW_NUMBERS SHOULD REFLECT STATUS HISTORY OF AN ORDER
    ,ROW_NUMBER() OVER (PARTITION BY _INT ORDER BY 1) AS RN
    -- RANDOM INTS ARE USED TO ASSIGN STATUSES
    ,FLOOR(1 + RANDOM() * 3) AS FIRST_RAND_INT
    ,FLOOR(1 + RANDOM() * 2) AS SECOND_RAND_INT
FROM
    ORDER_ID_TBL
