WITH CTE_PROVISION_RULES AS (
	SELECT
		_CHECK_SUM
		,PRODUCT_NAME
		,START_DATE
		,END_DATE
		,BASE_PROVISION
	FROM
		{{ ref('stage', '_stg_provision_rules') }}
	-- EACH RULE MUST ONLY APPEAR ONCE
	QUALIFY
		ROW_NUMBER() OVER (PARTITION BY _CHECK_SUM ORDER BY 1) = 1
)

SELECT
	CTE_PROVISION_RULES._CHECK_SUM
	,MAP_PRODUCT.PRODUCT_NAME
	,CTE_PROVISION_RULES.START_DATE
	,CTE_PROVISION_RULES.END_DATE
	,CTE_PROVISION_RULES.BASE_PROVISION
FROM CTE_PROVISION_RULES
LEFT OUTER JOIN {{ ref('mapping', 'provision_rules_product_mapping') }} AS MAP_PRODUCT
	ON CTE_PROVISION_RULES.PRODUCT_NAME = MAP_PRODUCT.PROVISION_RULES_PRODUCT_NAME
