WITH CTE AS (
	SELECT
		ORDER_ID
		,STATUS_NAME
		,PRODUCT_NAME
		,CREATION_DATE
		,STATUS_CHANGE_DATE
		-- SOMETIMES NOT EVERY RECORD FOR A TEST ORDER IS MARKED AS SUCH
		,ARRAY_AGG(DISTINCT IS_TEST_ORDER) OVER (PARTITION BY ORDER_ID) AS _ARR_IS_TEST_ORDER
		,CASE WHEN LIST_CONTAINS(_ARR_IS_TEST_ORDER,TRUE) THEN TRUE ELSE FALSE END AS IS_TEST_ORDER -- noqa: ST02
	FROM
		{{ ref('stage', 'stg_orders') }}
	{% if is_incremental() %}
		WHERE
			STATUS_CHANGE_DATE > (SELECT MAX(STATUS_CHANGE_DATE) AS WATERMARK FROM {{ this }})
	{% endif %}
)

SELECT
	ORDER_ID
	,STATUS_NAME
	,PRODUCT_NAME
	,CREATION_DATE
	,STATUS_CHANGE_DATE
	,IS_TEST_ORDER
FROM
	CTE
