SELECT
	_CHECK_SUM
	,PRODUCT_NAME
	,START_DATE
	,END_DATE
	,PROPORTIONAL_PROVISION_TARGET_VALUE
	,PROPORTIONAL_PROVISION_TARGET_UNIT
	,PROPORTIONAL_PROVISION_VALUE
FROM
  {{ ref('core','cre_provision_rules') }}
WHERE
	PROPORTIONAL_PROVISION_TARGET_VALUE IS NOT NULL