WITH CTE_PROVISION_RULES AS (
	SELECT
		_CHECK_SUM
		,PRODUCT_NAME
		,START_DATE
		,END_DATE
		,BASE_PROVISION
		,PLACEMENT_PROVISION
		,(PROPORTIONAL_PROVISION ->> 'target')::INTEGER AS PROPORTIONAL_PROVISION_TARGET_VALUE
		,(PROPORTIONAL_PROVISION ->> 'unit')::VARCHAR AS PROPORTIONAL_PROVISION_TARGET_UNIT
		,(PROPORTIONAL_PROVISION ->> 'value')::VARCHAR AS PROPORTIONAL_PROVISION_VALUE
	FROM
		{{ ref('stage', '_stg_provision_rules') }}
	QUALIFY
		ROW_NUMBER() OVER (PARTITION BY _CHECK_SUM ORDER BY 1) = 1
)

SELECT
	PROV_RULES._CHECK_SUM
	,MAP_PRODUCT.PRODUCT_NAME
	,PROV_RULES.START_DATE
	,PROV_RULES.END_DATE
	,PROV_RULES.BASE_PROVISION
	,PROV_RULES.PLACEMENT_PROVISION
	,PROV_RULES.PROPORTIONAL_PROVISION_TARGET_VALUE
	,PROV_RULES.PROPORTIONAL_PROVISION_TARGET_UNIT
	,PROV_RULES.PROPORTIONAL_PROVISION_VALUE
FROM CTE_PROVISION_RULES AS PROV_RULES
INNER JOIN {{ ref('mapping', 'provision_rules_product_mapping') }} AS MAP_PRODUCT
	ON PROV_RULES.PRODUCT_NAME = MAP_PRODUCT.PROVISION_RULES_PRODUCT_NAME
