WITH CTE_ORDERS AS (
	SELECT
		ORDER_ID
		,STATUS_NAME
		,PRODUCT_NAME
		,CREATION_DATE
		,STATUS_CHANGE_DATE
		-- SOMETIMES NOT EVERY RECORD FOR A TEST ORDER IS MARKED AS SUCH!!!
		,ARRAY_AGG(DISTINCT IS_TEST_ORDER) OVER (PARTITION BY ORDER_ID) AS _ARR_IS_INVALID
		,CASE WHEN LIST_CONTAINS(_ARR_IS_INVALID,TRUE) THEN TRUE ELSE FALSE END AS IS_INVALID_ORDER -- noqa: ST02
	FROM
		{{ ref('stg_orders') }}
	{% if is_incremental() %}
		WHERE
			CREATION_DATE > (SELECT MAX(CREATION_DATE) - 60 AS WATERMARK FROM {{ this }})
	{% endif %}
)

,CTE_ORDERS_ENRICHED AS (
	SELECT
		CTE_ORDERS.ORDER_ID
		,CTE_ORDERS.STATUS_NAME
		,CTE_ORDERS.PRODUCT_NAME
		,CTE_ORDERS.CREATION_DATE
		,CTE_ORDERS.STATUS_CHANGE_DATE
		,CTE_ORDERS.IS_INVALID_ORDER
		,CASE WHEN _PLACEMENT.ORDER_ID IS NOT NULL THEN TRUE ELSE FALSE END AS IS_PLACEMENT -- noqa: ST02
	FROM
		CTE_ORDERS
	LEFT OUTER JOIN
		{{ ref('stg_orders_with_placement') }} AS _PLACEMENT
		ON
			CTE_ORDERS.ORDER_ID = _PLACEMENT.ORDER_ID
)

SELECT
	ORDER_ID
	,STATUS_NAME
	,PRODUCT_NAME
	,CREATION_DATE
	,STATUS_CHANGE_DATE
	,IS_INVALID_ORDER
	,IS_PLACEMENT
FROM
	CTE_ORDERS_ENRICHED
