WITH CTE_NET_PROMOTOR_SCORES AS (
	SELECT
		RATING_DATE
		,RATING AS RATING_VALUE
		,SPLIT_PART(TRANSACTION_ID,'-',-1)::INTEGER AS ORDER_ID
		,UPPER(TOOL) AS RATING_TOOL
		,SPLIT_PART(TRANSACTION_ID,'-',1) AS PRODUCT_ABBREVIATION
		,CASE WHEN RATING BETWEEN 0 AND 10 THEN TRUE ELSE FALSE END AS IS_VALID_RATING -- noqa: ST02
	FROM
		{{ ref('stg_net_promotor_scores') }}
	{% if is_incremental() %}
		WHERE
			SPLIT_PART(TRANSACTION_ID,'-',-1)::INTEGER NOT IN (SELECT DISTINCT ORDER_ID FROM {{ this }})
	{% endif %}
)

,CTE_NET_PROMOTOR_SCORES_ENRICHED AS (
	SELECT
		_NPS.ORDER_ID
		,_MAP.PRODUCT_NAME
		,_NPS.RATING_DATE
		,_NPS.RATING_VALUE
		,_NPS.RATING_TOOL
		,_NPS.IS_VALID_RATING
	FROM
		CTE_NET_PROMOTOR_SCORES AS _NPS
	INNER JOIN {{ ref('map_net_promotor_scores_product_abbreviations') }} AS _MAP
		ON _NPS.PRODUCT_ABBREVIATION = _MAP.PRODUCT_ABBREVIATION
)

SELECT
	ORDER_ID
	,PRODUCT_NAME
	,RATING_DATE
	,RATING_VALUE
	,RATING_TOOL
	,IS_VALID_RATING
FROM
	CTE_NET_PROMOTOR_SCORES_ENRICHED
