WITH CTE AS (
	SELECT
		ORD_STATUS.ORDER_ID
		,MAP_PRODUCT.PRODUCT_NAME
		,MAP_PRODUCT.PRODUCT_TYPE
		,MAP_PRODUCT.PRODUCT_GROUP
		,ORD_STATUS.IS_PLACEMENT
		,ORD_STATUS.CURRENT_STATUS
		,ORD_STATUS.CREATION_DATE
		,ORD_STATUS.FORWARDING_DATE
		,ORD_STATUS.CONFIRMATION_DATE
		,ORD_STATUS.CANCELLATION_DATE
		,ORD_STATUS.IS_FORWARDED
		,ORD_STATUS.IS_CANCELLED
		,ORD_STATUS.IS_CONFIRMED
		-- GROSS BASE PROVISION CAN NEVER BE NULL
		,PROV_BASE_PLACE.GROSS_BASE_PROVISION
		,COALESCE(PROV_PROP.GROSS_PROPORTIONAL_PROVISION,0) AS GROSS_PROPORTIONAL_PROVISION
		,COALESCE(PROV_BASE_PLACE.GROSS_PLACEMENT_PROVISION,0) AS GROSS_PLACEMENT_PROVISION
		,COALESCE(PROV_BASE_PLACE.NET_BASE_PROVISION,0) AS NET_BASE_PROVISION
		,COALESCE(PROV_PROP.NET_PROPORTIONAL_PROVISION,0) AS NET_PROPORTIONAL_PROVISION
		,COALESCE(PROV_BASE_PLACE.NET_PLACEMENT_PROVISION,0) AS NET_PLACEMENT_PROVISION
	FROM
		{{ ref('int_orders_status_dates') }} AS ORD_STATUS
	LEFT OUTER JOIN
		{{ ref('map_product_hierarchy') }} AS MAP_PRODUCT
		ON
			ORD_STATUS.PRODUCT_NAME = MAP_PRODUCT.PRODUCT_NAME
			AND
			ORD_STATUS.CREATION_DATE BETWEEN MAP_PRODUCT.VALID_FROM AND MAP_PRODUCT.VALID_TO
	LEFT OUTER JOIN
		{{ ref('int_orders_base_placement_provisions') }} AS PROV_BASE_PLACE
		ON
			ORD_STATUS.ORDER_ID = PROV_BASE_PLACE.ORDER_ID
	LEFT OUTER JOIN
		{{ ref('int_orders_proportional_provisions') }} AS PROV_PROP
		ON
			ORD_STATUS.ORDER_ID = PROV_PROP.ORDER_ID
)

SELECT
	ORDER_ID
	,PRODUCT_NAME
	,PRODUCT_TYPE
	,PRODUCT_GROUP
	,IS_PLACEMENT
	,CURRENT_STATUS
	,CREATION_DATE
	,FORWARDING_DATE
	,CONFIRMATION_DATE
	,CANCELLATION_DATE
	,IS_FORWARDED
	,IS_CANCELLED
	,IS_CONFIRMED
	,GROSS_BASE_PROVISION
	,GROSS_PROPORTIONAL_PROVISION
	,GROSS_PLACEMENT_PROVISION
	,NET_BASE_PROVISION
	,NET_PROPORTIONAL_PROVISION
	,NET_PLACEMENT_PROVISION
FROM
	CTE
