version: 2

sources:
  - name: raw
    schema: raw_data
    description: "{{ doc('dsc_sources') }}"
    # For loader jinja function `doc` cannot be used
    loader: manual
    tags:
      - raw_data
    tables:
      - name: orders
        description: "{{ doc('dsc_tbl_orders') }}"
        columns:
          - name: _ID
            description: "{{ var('dsc_auto_id') }}"
            data_type: INTEGER
            data_tests:
              - not_null
              - unique
          - name: _ADDED_ON
            description: "{{ var('dsc_added_on') }}"
            data_type: TIMESTAMP
            data_tests:
              - not_null
          - name: LOAD_RESULT
            description: "{{ var('dsc_load_result') }}"
            data_type: JSON
            data_tests:
              - not_null
      - name: orders_with_placement
        description: "{{ doc('dsc_tbl_orders_with_placement') }}"
        columns:
          - name: _ID
            description: "{{ var('dsc_auto_id') }}"
            data_type: INTEGER
            data_tests:
              - not_null
              - unique
          - name: _ADDED_ON
            description: "{{ var('dsc_added_on') }}"
            data_type: TIMESTAMP
            data_tests:
              - not_null
          - name: LOAD_RESULT
            description: "{{ var('dsc_load_result') }}"
            data_type: JSON
            data_tests:
              - not_null
      - name: provision_rules
        description: "{{ doc('dsc_tbl_provision_rules') }}"
        columns:
          - name: _ID
            description: "{{ var('dsc_auto_id') }}"
            data_type: INTEGER
            data_tests:
              - not_null
              - unique
          - name: _ADDED_ON
            description: "{{ var('dsc_added_on') }}"
            data_type: TIMESTAMP
            data_tests:
              - not_null
          - name: LOAD_RESULT
            description: "{{ var('dsc_load_result') }}"
            data_type: JSON
            data_tests:
              - not_null
      - name: net_promotor_scores
        description: "{{ doc('dsc_tbl_net_promotor_scores') }}"
        columns:
          - name: _ID
            description: "{{ var('dsc_auto_id') }}"
            data_type: INTEGER
            data_tests:
              - not_null
              - unique
          - name: _ADDED_ON
            description: "{{ var('dsc_added_on') }}"
            data_type: TIMESTAMP
            data_tests:
              - not_null
          - name: TRANSACTION_ID
            description: "{{ var('dsc_transaction_id') }}"
            data_type: VARCHAR
            data_tests:
              - not_null
          - name: RATING_DATE
            description: "{{ var('dsc_rating_date') }}"
            data_type: DATE
            data_tests:
              - not_null
          - name: RATING
            description: "{{ var('dsc_rating_value') }}"
            data_type: INTEGER
            data_tests:
              - not_null
          - name: TOOL
            description: "{{ var('dsc_rating_tool') }}"
            data_type: VARCHAR
            data_tests:
              - not_null
      - name: exchange_rates
        description: "{{ doc('dsc_tbl_exchange_rates') }}"
        columns:
          - name: _ID
            description: "{{ var('dsc_auto_id') }}"
            data_type: INTEGER
            data_tests:
              - not_null
              - unique
          - name: _ADDED_ON
            description: "{{ var('dsc_added_on') }}"
            data_type: TIMESTAMP
            data_tests:
              - not_null
          - name: LOAD_RESULT
            description: "{{ var('dsc_load_result') }}"
            data_type: JSON
            data_tests:
              - not_null
