-- noqa: disable=RF04,ST02

CREATE OR REPLACE TEMP TABLE TMP_TEST_ORDERS AS
WITH CTE AS (
	SELECT
		(LOAD_RESULT ->> 'ORDER_ID')::INTEGER AS ORDER_ID
		,(LOAD_RESULT ->> 'IS_TEST_ORDER')::BOOLEAN AS IS_TEST_ORDER
	FROM
		RAW_DATA.ORDERS
)

SELECT ORDER_ID
FROM
	CTE
GROUP BY ALL
HAVING
	CASE WHEN LIST_CONTAINS(ARRAY_AGG(DISTINCT IS_TEST_ORDER),TRUE) THEN TRUE ELSE FALSE END = TRUE;

-- NPS

CREATE OR REPLACE TEMP TABLE NPS_BASE AS
WITH NPS AS (
	SELECT
		*
		,SPLIT_PART(TRANSACTION_ID,'-',1) AS PRODUCT_ABBREVIATION
	FROM
		RAW_DATA.NET_PROMOTOR_SCORES
	WHERE
		RATING BETWEEN 0 AND 10
		AND
		SPLIT_PART(TRANSACTION_ID,'-',-1)::INTEGER NOT IN (SELECT * FROM TMP_TEST_ORDERS)
)

SELECT
	YEAR(NPS.RATING_DATE) AS SURVEY_CALENDAR_YEAR
	,MONTH(NPS.RATING_DATE) AS SURVEY_CALENDAR_MONTH
	,MPH.PRODUCT_GROUP
	,MPH.PRODUCT_TYPE
	,MPH.PRODUCT_NAME
	,NPS.RATING AS RATING_VALUE
FROM
	NPS
LEFT OUTER JOIN
	MAPPING.MAP_NET_PROMOTOR_SCORES_PRODUCT_ABBREVIATIONS AS ABB
	ON NPS.PRODUCT_ABBREVIATION = ABB.PRODUCT_ABBREVIATION
LEFT OUTER JOIN
	MAPPING.MAP_PRODUCT_HIERARCHY AS MPH
	ON
		ABB.PRODUCT_NAME = MPH.PRODUCT_NAME
		AND
		NPS.RATING_DATE BETWEEN MPH.VALID_FROM AND MPH.VALID_TO;

CREATE OR REPLACE TEMP TABLE _SQL_APPR AS
SELECT
	-- DIMS
	SURVEY_CALENDAR_YEAR
	,SURVEY_CALENDAR_MONTH
	,'TOTAL' AS PRODUCT_GROUP
	,'TOTAL' AS PRODUCT_TYPE
	,'TOTAL' AS PRODUCT_NAME
	-- METRICS
	,COUNT(*) AS PARTICIPANTS
	,COUNT_IF(RATING_VALUE <= 6) AS DETRACTORS
	,COUNT_IF(RATING_VALUE IN (7,8)) AS INDIFFERENTS
	,COUNT_IF(RATING_VALUE >= 9) AS PROMOTORS
	,'TOTAL' AS AGGREGATION_LEVEL
FROM NPS_BASE
GROUP BY ALL
UNION ALL
SELECT
	-- DIMS
	SURVEY_CALENDAR_YEAR
	,SURVEY_CALENDAR_MONTH
	,PRODUCT_GROUP
	,'TOTAL' AS PRODUCT_TYPE
	,'TOTAL' AS PRODUCT_NAME
	-- METRICS
	,COUNT(*) AS PARTICIPANTS
	,COUNT_IF(RATING_VALUE <= 6) AS DETRACTORS
	,COUNT_IF(RATING_VALUE IN (7,8)) AS INDIFFERENTS
	,COUNT_IF(RATING_VALUE >= 9) AS PROMOTORS
	,'PRODUCT_GROUP' AS AGGREGATION_LEVEL
FROM NPS_BASE
GROUP BY ALL
UNION ALL
SELECT
	-- DIMS
	SURVEY_CALENDAR_YEAR
	,SURVEY_CALENDAR_MONTH
	,PRODUCT_GROUP
	,PRODUCT_TYPE
	,'TOTAL' AS PRODUCT_NAME
	-- METRICS
	,COUNT(*) AS PARTICIPANTS
	,COUNT_IF(RATING_VALUE <= 6) AS DETRACTORS
	,COUNT_IF(RATING_VALUE IN (7,8)) AS INDIFFERENTS
	,COUNT_IF(RATING_VALUE >= 9) AS PROMOTORS
	,'PRODUCT_TYPE' AS AGGREGATION_LEVEL
FROM NPS_BASE
GROUP BY ALL
UNION ALL
SELECT
	-- DIMS
	SURVEY_CALENDAR_YEAR
	,SURVEY_CALENDAR_MONTH
	,PRODUCT_GROUP
	,PRODUCT_TYPE
	,PRODUCT_NAME
	-- METRICS
	,COUNT(*) AS PARTICIPANTS
	,COUNT_IF(RATING_VALUE <= 6) AS DETRACTORS
	,COUNT_IF(RATING_VALUE IN (7,8)) AS INDIFFERENTS
	,COUNT_IF(RATING_VALUE >= 9) AS PROMOTORS
	,'PRODUCT_NAME' AS AGGREGATION_LEVEL
FROM NPS_BASE
GROUP BY ALL;

CREATE OR REPLACE TEMP TABLE _DBT_APPR AS
SELECT
	SURVEY_CALENDAR_YEAR
	,SURVEY_CALENDAR_MONTH
	,PRODUCT_GROUP
	,PRODUCT_TYPE
	,PRODUCT_NAME
	,PARTICIPANTS
	,DETRACTORS
	,INDIFFERENTS
	,PROMOTORS
	,AGGREGATION_LEVEL
FROM MARTS.MRT_NET_PROMOTOR_SCORES;

(
	SELECT *
	FROM _SQL_APPR
	EXCEPT
	SELECT *
	FROM _DBT_APPR
)
UNION ALL
(
	SELECT *
	FROM _DBT_APPR
	EXCEPT
	SELECT *
	FROM _SQL_APPR
);
