-- BELOW QUERY WILL RETURN A QUERY THAT CHECKS IF ANY COLUMN LEVEL TEST FAILED
-- NOTE: THIS DOES NOT INCLUDE DBT MODELS THAT ARE MATERIALIZED AS CTES

WITH CTE_TESTS AS (
	SELECT
		TABLE_SCHEMA
		,TABLE_NAME
	FROM
		INFORMATION_SCHEMA.TABLES --noqa
	WHERE
		UPPER(TABLE_SCHEMA) = 'DBT_TEST__AUDIT'
)

,CTE_FILTER AS (
	SELECT TABLE_NAME AS _TBL
	FROM
		INFORMATION_SCHEMA.TABLES --noqa
	WHERE
		UPPER(TABLE_SCHEMA) NOT IN ('DBT_TEST__AUDIT','MAIN','RAW_DATA')
)

SELECT
	STRING_AGG(
		CONCAT($$SELECT '$$,TABLE_NAME,$$' AS TBL
		,COUNT(*) = 0 AS TEST_PASSED FROM DBT_TEST__AUDIT.$$ || TABLE_NAME),' UNION ALL '
	) AS QRY
FROM
	CTE_TESTS
WHERE
	STRING_SPLIT(TABLE_NAME,'__')[1] IN (SELECT _TBL FROM CTE_FILTER) --noqa
	AND
	LEN(STRING_SPLIT(TABLE_NAME,'__')) = 3;
