-- sqlfluff:rules:references.keywords:ignore_words:HEADER,JSON

/*
ORDERS
*/

-- LOAD CSV

CREATE OR REPLACE TEMPORARY TABLE TMP_ORDERS AS
SELECT COLUMNS(*)
FROM
	READ_CSV(
		'/workspaces/analytics/duckdb_analytics/update_db/sample_data/orders.csv'
		,ALL_VARCHAR = TRUE
		,HEADER = TRUE
		,SEP = ','
	);

INSERT INTO RAW_DATA.ORDERS (LOAD_RESULT)
SELECT
	{
		'ORDER_ID': ORDER_ID
		,'STATUS_NAME': STATUS_NAME
		,'PRODUCT_NAME': PRODUCT_NAME
		,'CREATION_DATE': CREATION_DATE
		,'STATUS_CHANGE_DATE': STATUS_CHANGE_DATE
		,'IS_TEST_ORDER': IS_TEST_ORDER
	}::JSON AS LOAD_RESULT
FROM
	TMP_ORDERS;

DROP TABLE IF EXISTS TMP_ORDERS;

/*
NET PROMOTOR SCORE (NPS)
*/

CREATE OR REPLACE TEMPORARY TABLE TMP_NPS AS
SELECT JSON AS LOAD_RESULT
FROM
	READ_JSON(
		'/workspaces/analytics/duckdb_analytics/update_db/sample_data/nps.json'
		,RECORDS = FALSE
	);

INSERT INTO RAW_DATA.NET_PROMOTOR_SCORES (TRANSACTION_ID,RATING_DATE,RATING,TOOL)
WITH CTE AS (
	SELECT
		JSON_EXTRACT_STRING(
			LOAD_RESULT,['TRANSACTION_ID','RATING_DATE','RATING','TOOL']
		) AS _EXTRACT
	FROM TMP_NPS
)

SELECT
	_EXTRACT[1]::VARCHAR AS TRANSACTION_ID
	,_EXTRACT[2]::DATE AS RATING_DATE
	,_EXTRACT[3]::INTEGER AS RATING
	,_EXTRACT[4]::VARCHAR AS TOOL
FROM
	CTE;

DROP TABLE IF EXISTS TMP_NPS;
