name: "dbt_analytics"
version: "1.0.0"

profile: "dbt_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "logs"
  - "target"

models:
  dbt_analytics:
    # incremental models require this setting so we keep it as default
    +on_schema_change: append_new_columns
    +persist_docs:
      relation: true
      columns: true

    # set tags for schemas
    stage:
      +tags: stage
    core:
      +tags: core
    intermediate:
      +tags: intermediate
    marts:
      +tags: marts

  # config for package `dbt_project_evaluator`
  dbt_project_evaluator:
    marts:
      structure:
        fct_model_naming_conventions:
          +enabled: false
        fct_model_directories:
          +enabled: false
      tests:
        fct_sources_without_freshness:
          +enabled: false

seeds:
  +persist_docs:
    relation: true
    columns: true
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

snapshots:
  +persist_docs:
    relation: true
    columns: true

sources:
  +enabled: true

data_tests:
  +store_failures: true

on-run-end:
  - "{{ run_vacuum_analyze() }}"
  - "{{ check_for_cols_without_comments() }}"
  - "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"

query-comment:
  append: True

flags:
  partial_parse: false
  printer_width: 120
  send_anonymous_usage_stats: False

vars:
  # these schemas do not contain data used/generated by models
  ignored_schemas: "'dbt_test__audit','main'"

  ### default descriptions
  dsc_auto_id: "Incremental id"
  dsc_added_on: "Timestamp when record was added"
  dsc_valid_from: "Date since when record is valid"
  dsc_valid_to: "Date since until record is valid"
  dsc_load_result: "Raw load result"
  dsc_hash_key: "Surrogate key based on natural key or concatenation of multiple attributes"

  ### calendar
  dsc_calendar_date: "Calendar date"
  dsc_calendar_week: "Calendar week of year"
  dsc_calendar_month: "Calendar month of year"
  dsc_calendar_quarter: "Calendar quarter of year"
  dsc_calendar_year: "Calendar year"
  dsc_calendar_day_name: "Name of day"
  dsc_calendar_is_weekend: "Flag if calendar date is on a weekend"

  ### product_hierarchy
  dsc_product_group: "Highest level of product hierarchy"
  dsc_product_type: "Middle level of product hierarchy"
  dsc_product_name: "Lowest level of product hierarchy"

  ### orders
  dsc_order_id: "Identifier of an order"
  dsc_status_name: "Status of an order"
  dsc_ord_product_name: "Name of the product ordered"
  dsc_creation_date: "Date of order creation"
  dsc_status_change_date: "Date of order status change"
  dsc_is_test_order: "Flag if order is a test"
  # derived cols
  dsc_is_invalid_order: "Flag if order is invalid (= test order)"
  dsc_is_placement: "Flag if order is with placement"
  dsc_current_status: "Current status of an order"
  dsc_forwarding_date: "Date of order forwarding"
  dsc_confirmation_date: "Date of order confirmation"
  dsc_cancellation_date: "Date of order cancellation"
  dsc_is_forwarded: "Flag if order is forwarded"
  dsc_is_confirmed: "Flag if order is confirmed"
  dsc_is_cancelled: "Flag if order is cancelled"

  ### provision rules
  dsc_start_date: "Date since when rule is valid"
  dsc_end_date: "Date until rule is valid"
  dsc_prov_product_name: "Name of the product to which a particular rule applies"
  dsc_base_provision: "Base provision according to a particular rule"
  dsc_placement_provision: "Placement provision according to a particular rule"
  dsc_proportional_provision: "Proportional provision according to a particular rule"
  dsc_proportional_provision_target_value: "Target value (= amount of orders) to be reached according to a particular rule"
  dsc_proportional_provision_target_unit: "Unit of target value e.g. 'month' means that target value needs to be reached within one month"
  dsc_check_sum: "Identifier of a particular rule"
  # gross
  dsc_gross_base_provision: "Gross base provision of an order (all orders)"
  dsc_gross_placement_provision: "Gross placement provision of an order (all orders if applicable)"
  dsc_gross_proportional_provision: "Gross proportional provision of an order (all orders if applicable)"
  # net
  dsc_net_base_provision: "Net base provision of an order (only confirmed orders)"
  dsc_net_placement_provision: "Net placement provision of an order (only confirmed orders if applicable)"
  dsc_net_proportional_provision: "Net proportional provision of an order (only confirmed orders if applicable)"

  ### net promotor scores
  dsc_transaction_id: "Concatenation of product name prefix and order id"
  dsc_rating_date: "Date of rating"
  dsc_rating_value: "NPS rating by customer"
  dsc_rating_tool: "Tool used to collect rating"
  dsc_is_valid_rating: "Flag if rating is between 0 and 10 (= valid)"
  dsc_survey_order_id: "Identifier of order that triggered the survey"
  dsc_survey_calendar_year: "Calendar year (related to survey)"
  dsc_survey_calendar_month: "Calendar month of year (related to survey)"
  dsc_survey_product_name: "Name of ordered product that triggered the survey"
  dsc_survey_product_type: "Name of ordered product type that triggered the survey"
  dsc_survey_product_group: "Name of ordered product group that triggered the survey"

  ### partners
  dsc_partner_updated_on: "date since when we cooperate with partner"
  dsc_partner_product_name: "name of product that partner handles"
  dsc_partner_name: "name of partner"
