name: "dbt_analytics"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_analytics"

# These configurations specify where dbt should look for different types of files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "logs"
  - "target"

models:
  +persist_docs:
    relation: true
    columns: true

seeds:
  +persist_docs:
    relation: true
    columns: true

sources:
  +enabled: true

query-comment:
  append: True

vars:
  ### default descriptions

  dsc_valid_from: "Date since when mapping is valid"
  dsc_valid_to: "Date since until mapping is valid"
  # product_hierarchy
  dsc_product_group: "Highest level of product hierarchy"
  dsc_product_type: "Middle level of product hierarchy"
  dsc_product_name: "Lowest level of product hierarchy"
  # orders
  dsc_order_id: "Identifier of an order"
  dsc_status_name: "Status of an order"
  dsc_ord_product_name: "Name of the product ordered"
  dsc_creation_date: "Date when order was created"
  dsc_status_change_date: "Date when status of an order was changed"
  dsc_is_test_order: "Flag if order was a test"
