dbt_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DB_PATH') }}"
      threads: 1
    prod:
      type: duckdb
      path: "md:ANALYTICS?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      threads: 1
