-- ORDERS

CREATE SEQUENCE IF NOT EXISTS RAW_DATA.ORDERS_SEQ START 1;

CREATE TABLE IF NOT EXISTS RAW_DATA.ORDERS
(
	_ID INTEGER NOT NULL DEFAULT NEXTVAL('RAW_DATA.ORDERS_SEQ')
	,_ADDED_ON TIMESTAMP DEFAULT GET_CURRENT_TIMESTAMP()
	,LOAD_RESULT JSON NOT NULL
);

COMMENT ON TABLE RAW_DATA.ORDERS IS
'CONTAINS RAWDATA FOR ORDERS (APPEND ONLY)';

COMMENT ON COLUMN RAW_DATA.ORDERS._ID IS
'INCREMENTAL AUTO-ID USING SEQUENCE';

COMMENT ON COLUMN RAW_DATA.ORDERS._ADDED_ON IS
'TIMESTAMP WHEN ROW WAS ADDED';

COMMENT ON COLUMN RAW_DATA.ORDERS.LOAD_RESULT IS
'RAW RESULT OF LOAD';

-- PROVISION RULES

CREATE SEQUENCE IF NOT EXISTS RAW_DATA.PROVISION_RULES_SEQ START 1;

CREATE TABLE IF NOT EXISTS RAW_DATA.PROVISION_RULES
(
	_ID INTEGER NOT NULL DEFAULT NEXTVAL('RAW_DATA.PROVISION_RULES_SEQ')
	,_ADDED_ON TIMESTAMP DEFAULT GET_CURRENT_TIMESTAMP()
	,LOAD_RESULT JSON NOT NULL
);

COMMENT ON TABLE RAW_DATA.PROVISION_RULES IS
'CONTAINS RAWDATA FOR PROVISION RULES (APPEND ONLY)';

COMMENT ON COLUMN RAW_DATA.PROVISION_RULES._ID IS
'INCREMENTAL AUTO-ID USING SEQUENCE';

COMMENT ON COLUMN RAW_DATA.PROVISION_RULES._ADDED_ON IS
'TIMESTAMP WHEN ROW WAS ADDED';

COMMENT ON COLUMN RAW_DATA.PROVISION_RULES.LOAD_RESULT IS
'RAW RESULT OF LOAD';
