SELECT
	DATE_TRUNC('DAY',GENERATE_SERIES) AS CALENDAR_DATE
	,WEEK(CALENDAR_DATE) AS CALENDAR_WEEK
	,MONTH(CALENDAR_DATE) AS CALENDAR_MONTH
	,QUARTER(CALENDAR_DATE) AS CALENDAR_QUARTER
	,YEAR(CALENDAR_DATE) AS CALENDAR_YEAR
	,DAYNAME(CALENDAR_DATE) AS CALENDAR_DAY_NAME
	,CASE WHEN CALENDAR_DAY_NAME IN ('Saturday','Sunday') THEN TRUE ELSE FALSE END AS IS_WEEKEND -- noqa: ST02
FROM
	GENERATE_SERIES('2020-01-01'::DATE,'2030-12-31'::DATE,INTERVAL 1 DAY)
