WITH CTE_ORDERS AS (
	SELECT
		DATE_TRUNC('MONTH',CREATION_DATE) AS CREATION_MONTH
		-- SUM UP ALL PROVISION TYPES TO GET GROSS/ NET PROVISION
		,SUM(GROSS_BASE_PROVISION + GROSS_PROPORTIONAL_PROVISION + GROSS_PLACEMENT_PROVISION) AS GROSS_PROVISION
		,SUM(NET_BASE_PROVISION + NET_PROPORTIONAL_PROVISION + NET_PLACEMENT_PROVISION) AS NET_PROVISION
	FROM
		{{ ref('mrt_orders') }}
	WHERE
		CREATION_DATE < '2023-12-01'
	GROUP BY
		ALL
)

SELECT
	CTE_ORDERS.CREATION_MONTH
	,ECR.EXCHANGE_RATE
	,ROUND(CTE_ORDERS.GROSS_PROVISION,0) AS GROSS_PROVISION_IN_EUR
	,ROUND(CTE_ORDERS.NET_PROVISION,0) AS NET_PROVISION_IN_EUR
	,ROUND(CTE_ORDERS.GROSS_PROVISION * ECR.EXCHANGE_RATE,0) AS GROSS_PROVISION_IN_USD
	,ROUND(CTE_ORDERS.NET_PROVISION * ECR.EXCHANGE_RATE,0) AS NET_PROVISION_IN_USD
FROM
	CTE_ORDERS
-- EXACT MATCH NOT POSSIBLE
ASOF JOIN
	{{ ref('stg_exchange_rates') }} AS ECR
	ON
		CTE_ORDERS.CREATION_MONTH <= ECR.VALID_FROM
ORDER BY
	CTE_ORDERS.CREATION_MONTH
