WITH CTE_ORDERS AS (
	SELECT
		DATE_TRUNC('MONTH',CREATION_DATE) AS CREATION_MONTH
		,COUNT(*) AS CNT_ORDERS
	FROM
		{{ ref('mrt_orders') }}
	WHERE
		TRUE
		AND
		PRODUCT_GROUP = 'DOMAINS_&_HOSTING'
	GROUP BY
		ALL
)

,CTE_NPS AS (
	SELECT
		NET_PROMOTOR_SCORE
		,MAKE_DATE(SURVEY_CALENDAR_YEAR,SURVEY_CALENDAR_MONTH,1) AS CREATION_MONTH
	FROM
		{{ ref('mrt_net_promotor_scores') }}
	WHERE
		TRUE
		AND
		AGGREGATION_LEVEL = 'PRODUCT_GROUP'
		AND
		PRODUCT_GROUP = 'DOMAINS_&_HOSTING'
)

SELECT CORR(CTE_ORDERS.CNT_ORDERS,CTE_NPS.NET_PROMOTOR_SCORE) AS _CORR
FROM
	CTE_ORDERS
LEFT OUTER JOIN
	CTE_NPS
	ON
		CTE_ORDERS.CREATION_MONTH = CTE_NPS.CREATION_MONTH
