name: Run CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5
      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_cicd.txt
      - name: Set env variable for PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/duckdb_analytics" >> $GITHUB_ENV
      - name: Deploy to MotherDuck
        env:
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd duckdb_analytics/initialize_db
          python execute_initialization.py
