name: Run CI
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5
      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_cicd.txt
      - name: Set env variable for PYTHONPATH
        id: env-var-python-path
        run: echo "PYTHONPATH=$(pwd)/duckdb_analytics" >> $GITHUB_ENV
      - name: Get changed Python files
        id: changed-py-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            *.py
            **/*.py
      - name: Lint with Pylint
        if: steps.changed-py-files.outputs.any_changed == 'true'
        env:
          PYTHONPATH: ${{ steps.env-var-python-path.outputs.PYTHONPATH }}
        run: pylint ${{ steps.changed-py-files.outputs.all_changed_files }}
      - name: Lint with isort
        if: steps.changed-py-files.outputs.any_changed == 'true'
        env:
          PYTHONPATH: ${{ steps.env-var-python-path.outputs.PYTHONPATH }}
        run: isort ${{ steps.changed-py-files.outputs.all_changed_files }}
      - name: Lint with flake8
        if: steps.changed-py-files.outputs.any_changed == 'true'
        env:
          PYTHONPATH: ${{ steps.env-var-python-path.outputs.PYTHONPATH }}
        run: flake8 ${{ steps.changed-py-files.outputs.all_changed_files }} --verbose
      - name: Format with black
        if: steps.changed-py-files.outputs.any_changed == 'true'
        env:
          PYTHONPATH: ${{ steps.env-var-python-path.outputs.PYTHONPATH }}
        run: black ${{ steps.changed-py-files.outputs.all_changed_files }} --check --diff --verbose
      - name: Test with pytest
        if: steps.changed-py-files.outputs.any_changed == 'true'
        env:
          PYTHONPATH: ${{ steps.env-var-python-path.outputs.PYTHONPATH }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd tests
          pytest
      - name: Get changed dbt analyses & models
        id: changed-dbt-analyses-models
        uses: tj-actions/changed-files@v45
        with:
          files: "dbt_analytics/analyses/**/*.sql|dbt_analytics/models/**/*.sql"
      - name: Lint dbt analyses & models with SQLFluff
        if: steps.changed-dbt-analyses-models.outputs.any_changed == 'true'
        run: sqlfluff lint ${{ steps.changed-dbt-analyses-models.outputs.all_changed_files }}
      - name: Get changed DuckDB SQL files
        id: changed-duckdb-sql-files
        uses: tj-actions/changed-files@v45
        with:
          files: "duckdb_analytics/**/*.sql"
      - name: Lint DuckDB SQL files with SQLFluff
        if: steps.changed-duckdb-sql-files.outputs.any_changed == 'true'
        run: sqlfluff lint ${{ steps.changed-duckdb-sql-files.outputs.all_changed_files }}
      - name: Format with prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_options: "--check **/*.{json,md,yaml,yml}"
          only_changed: True
