name: Run CI
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5
      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pylint
        env:
          PYTHONPATH: ${{ vars.PYTHONPATH }}
        run: |
          pylint $(git diff --name-only --cached | grep '.py$')
      - name: isort
        env:
          PYTHONPATH: ${{ vars.PYTHONPATH }}
        run: |
          isort $(git diff --name-only --cached | grep '.py$') --check-only --diff
      - name: Lint with flake8
        uses: py-actions/flake8@v2
        with:
          args: "--vv"
          exclude: ".venv"
      - name: Format with black
        uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
      - name: Test with pytest
        env:
          PYTHONPATH: ${{ vars.PYTHONPATH }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd tests
          pytest
      - name: Lint dbt analyses & models with SQLFluff
        run: |
          sqlfluff lint $(git diff --name-only --cached | grep '.sql$' | grep -E 'dbt_analytics/(analyses|models)')
      - name: Lint DuckDB SQL files with SQLFluff
        run: |
          sqlfluff lint $(git diff --name-only --cached | grep '.sql$' | grep 'duckdb_analytics')
      - name: Format with prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_options: "--check **/*.{json,md,yaml,yml}"
          only_changed: True
