name: Run dbt
on:
  workflow_dispatch:
    inputs:
      clone_db:
        description: Flag to indicate if db shall be cloned after `dbt build`
        required: true
        default: "true"
        type: choice
        options:
          - true
          - false
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5
      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_cicd.txt
      - name: Install dbt dependencies
        run: |
          cd dbt_analytics
          dbt deps
      - name: dbt build
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd dbt_analytics
          dbt build --target prod
      - name: Clone database
        if: ${{ inputs.clone_db }}
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd dbt_analytics
          dbt run-operation zero_copy_clone_db --args '{tgt_db: ANALYTICS_PROD, src_db: ANALYTICS}' --target prod
