name: Run Python Tests

on:
  push:
    branches: [main]
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ vars.PYTHONPATH }}
          MOTHERDUCK_SECRET: ${{ secrets.MOTHERDUCK_SECRET }}
        run: |
          cd tests
          pytest
